[package]
name = "solana-escrow-contract-example"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.7.10"
thiserror = "1.0.24"
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}

[lib]
crate-type = ["cdylib", "lib"]
